# Generated by Django 3.1 on 2024-12-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_burger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('priceM', models.DecimalField(decimal_places=2, max_digits=4)),
                ('priceL', models.DecimalField(decimal_places=2, max_digits=4)),
                ('dImage', models.URLField()),
            ],
        ),
    ]
