# Generated by Django 3.1 on 2024-12-08 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_drinks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drinks',
            new_name='Drink',
        ),
    ]