# Generated by Django 3.1 on 2024-12-08 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20241208_0335'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drink',
            new_name='Beverage',
        ),
    ]
